pub const INTEGER_TAG: u8 = 0x02;
pub const OCTET_STRING_TAG: u8 = 0x04;
pub const BIT_STRING_TAG: u8 = 0x03;
pub const SEQUENCE_TAG: u8 = 0x30;
pub const OBJECT_IDENTIFIER_TAG: u8 = 0x06;
pub const SET_TAG: u8 = 0x31;
pub const BOOLEAN_TAG: u8 = 0x01;
pub const UTF8STRING_TAG: u8 = 0x0C;
pub const GENERALIZED_TIME_TAG: u8 = 0x18;
pub const NULL_TAG: u8 = 0x05;
pub const CONTEXT_SPECIFIC_0_TAG: u8 = 0xA0; // hard coded to be followed by a seq
pub const LONG_FORM_DECODE: u8 = 0x7F;
pub const LONG_FORM: u8 = 0x80;
